name: C++
on:
  push:
  pull_request:
jobs:
  windows-latest:
    runs-on: 'windows-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Get GoogleTest
      run: git submodule update --init
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build tests
      run: msbuild CPP/Tests/VisualStudio/Tests_cpp.sln /p:Configuration=Release /p:Platform=x64
    - name: Run tests
      run: x64\Release\Tests.exe
      working-directory: CPP/Tests/VisualStudio
    - name: Build console demo program
      run: msbuild CPP/Examples/ConsoleDemo1/ConsoleDemo1_cpp.sln
    - name: Build inflate demo application
      run: msbuild CPP/Examples/InflateDemo/InflateDemoApp.sln
  ubuntu-latest-gcc-default:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Get GoogleTest
      run: git submodule update --init
    - name: Build
      run: |
        mkdir CPP/build
        cd CPP/build
        cmake ..
        make
    - name: Run tests
      run: |
        cd CPP/build
        make test
  ubuntu-latest-gcc-11:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Get GoogleTest
      run: git submodule update --init
    - name: Install gcc 11
      run: |
        sudo apt update
        sudo apt install gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
    - name: Build
      run: |
        mkdir CPP/build
        cd CPP/build
        cmake ..
        make
    - name: Run tests
      run: |
        cd CPP/build
        make test
  ubuntu-latest-clang-default:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Get GoogleTest
      run: git submodule update --init
    - name: Build
      run: |
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        mkdir CPP/build
        cd CPP/build
        cmake ..
        make
    - name: Run tests
      run: |
        cd CPP/build
        make test
  ubuntu-latest-clang-13:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Get GoogleTest
      run: git submodule update --init
    - name: Install clang 13
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 13
    - name: Build
      run: |
        export CC=/usr/bin/clang-13
        export CXX=/usr/bin/clang++-13
        mkdir CPP/build
        cd CPP/build
        cmake ..
        make
    - name: Run tests
      run: |
        cd CPP/build
        make test
  macos-latest:
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Get GoogleTest
      run: git submodule update --init
    - name: Build
      run: |
        mkdir CPP/build
        cd CPP/build
        cmake ..
        make
    - name: Run tests
      run: |
        cd CPP/build
        make test
